### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by qw-in** [odwyersoftware/brunette#22]
Black supports pyproject.toml now but brunette does not seem to yet. Would be nice to have. Thanks!

**Comment by qw-in** [comment]
Oh, it appears to work when placed under `tool.black`:

```toml
[tool.black]
line_length = 99
skip_string_normalization = true
single_quotes = true
```
